import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import regionsRouter from "./regions";
import schoolsRouter from "./schools";
import lookupsRouter from "./lookups";
import entitiesRouter from "./entities";
import fiscalYearEntityGoalsRouter from "./fiscalYearEntityGoals";
import householdsRouter from "./households";
import paymentIntermediariesRouter from "./paymentIntermediaries";
import organizationsRouter from "./organizations";
import peopleRouter from "./people";
import peopleEntityRolesRouter from "./peopleEntityRoles";
import donorPaymentIntermediariesRouter from "./donorPaymentIntermediaries";
import emailsRouter from "./emails";
import phoneNumbersRouter from "./phoneNumbers";
import addressesRouter from "./addresses";
import opportunitiesRouter from "./opportunitiesAndPledges";
import pledgeAllocationsRouter from "./pledgeAllocations";
import giftsRouter from "./giftsAndPayments";
import giftAllocationsRouter from "./giftAllocations";
import analyticsRouter from "./analytics";
import interactionsRouter from "./interactions";
import googleOauthRouter from "./googleOauth";
import googleSyncRouter from "./googleSync";
import emailMessagesRouter from "./emailMessages";
import emailAttachmentsRouter from "./emailAttachments";
import calendarEventsRouter from "./calendarEvents";
import adminSyncRouter from "./adminSync";
import emailIntelAdminRouter from "./emailIntelAdmin";
import emailProposalsRouter from "./emailProposals";
import taskProposalsRouter from "./taskProposals";
import correspondentsRouter from "./correspondents";
import notesRouter from "./notes";
import mediaMentionsRouter from "./mediaMentions";
import tasksRouter from "./tasks";
import meetingNotesRouter from "./meetingNotes";
import savedViewsRouter from "./savedViews";
import storageRouter from "./storage";
import emailTrackingRouter from "./emailTracking";
import suppressionWindowsRouter from "./suppressionWindows";
import calendarMeetingFiltersRouter from "./calendarMeetingFiltersRoute";
import internalEmailDomainsRouter from "./internalEmailDomainsRoute";
import wildflowerUpdatesRouter from "./wildflowerUpdatesRoute";
import topPrioritiesRouter from "./topPriorities";
import quickbooksOauthRouter from "./quickbooksOauth";
import quickbooksRouter from "./quickbooks";
import quickbooksRulesRouter from "./quickbooksRules";
import revenueCodingRouter from "./revenueCoding";
import revenueExtractorRouter from "./revenueExtractor";
import stripeLedgerReadsRouter from "./stripeLedgerReads";
import stripeLedgerActionsRouter from "./stripeLedgerActions";
import stripeRouter from "./stripe";
import donorboxRouter from "./donorbox";
import grantLeadsRouter from "./grantLeads";
import auditLogRouter from "./auditLog";
import searchRouter from "./search";
import potentialDuplicatesRouter from "./potentialDuplicates";
import financialCorrectionsRouter from "./financialCorrections";
import cleanupQueueRouter from "./cleanupQueue";
import adminReassignRouter from "./adminReassign";
import reconciliationRouter from "./reconciliation";
import codingFormRowsRouter from "./codingFormRows";

const router: IRouter = Router();

router.use(healthRouter);
router.use(emailTrackingRouter);
router.use(usersRouter);
router.use(regionsRouter);
router.use(schoolsRouter);
router.use(lookupsRouter);
router.use(entitiesRouter);
router.use(fiscalYearEntityGoalsRouter);
router.use(householdsRouter);
router.use(paymentIntermediariesRouter);
router.use(organizationsRouter);
router.use(peopleRouter);
router.use(peopleEntityRolesRouter);
router.use(donorPaymentIntermediariesRouter);
router.use(emailsRouter);
router.use(phoneNumbersRouter);
router.use(addressesRouter);
router.use(opportunitiesRouter);
router.use(pledgeAllocationsRouter);
router.use(giftsRouter);
router.use(giftAllocationsRouter);
router.use(analyticsRouter);
router.use(interactionsRouter);
router.use(googleOauthRouter);
router.use(googleSyncRouter);
router.use(emailMessagesRouter);
router.use(emailAttachmentsRouter);
router.use(calendarEventsRouter);
router.use(adminSyncRouter);
router.use(emailIntelAdminRouter);
router.use(emailProposalsRouter);
router.use(taskProposalsRouter);
router.use(correspondentsRouter);
router.use(notesRouter);
router.use(mediaMentionsRouter);
router.use(tasksRouter);
router.use(meetingNotesRouter);
router.use(savedViewsRouter);
router.use(storageRouter);
router.use(suppressionWindowsRouter);
router.use(calendarMeetingFiltersRouter);
router.use(internalEmailDomainsRouter);
router.use(wildflowerUpdatesRouter);
router.use(topPrioritiesRouter);
router.use(quickbooksOauthRouter);
router.use(quickbooksRouter);
router.use(quickbooksRulesRouter);
router.use(revenueCodingRouter);
router.use(revenueExtractorRouter);
// Ledger-authoritative Stripe reads and normal link/mint actions mount before the
// remaining legacy Stripe endpoints. The explicit source-switch action falls
// through until its orphan/unwind workflow is migrated.
router.use(stripeLedgerReadsRouter);
router.use(stripeLedgerActionsRouter);
router.use(stripeRouter);
router.use(donorboxRouter);
router.use(grantLeadsRouter);
router.use(auditLogRouter);
router.use(searchRouter);
router.use(potentialDuplicatesRouter);
router.use("/financial-corrections", financialCorrectionsRouter);
router.use(cleanupQueueRouter);
router.use(adminReassignRouter);
router.use(reconciliationRouter);
router.use(codingFormRowsRouter);

export default router;
