import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import regionsRouter from "./regions";
import schoolsRouter from "./schools";
import lookupsRouter from "./lookups";
import entitiesRouter from "./entities";
import fiscalYearEntityGoalsRouter from "./fiscalYearEntityGoals";
import householdsRouter from "./households";
import paymentIntermediariesRouter from "./paymentIntermediaries";
import fundersRouter from "./funders";
import organizationsRouter from "./organizations";
import peopleRouter from "./people";
import peopleEntityRolesRouter from "./peopleEntityRoles";
import emailsRouter from "./emails";
import phoneNumbersRouter from "./phoneNumbers";
import addressesRouter from "./addresses";
import opportunitiesRouter from "./opportunitiesAndPledges";
import pledgeAllocationsRouter from "./pledgeAllocations";
import giftsRouter from "./giftsAndPayments";
import giftAllocationsRouter from "./giftAllocations";
import analyticsRouter from "./analytics";
import interactionsRouter from "./interactions";
import googleOauthRouter from "./googleOauth";
import googleSyncRouter from "./googleSync";
import emailMessagesRouter from "./emailMessages";
import emailAttachmentsRouter from "./emailAttachments";
import calendarEventsRouter from "./calendarEvents";
import adminSyncRouter from "./adminSync";
import emailProposalsRouter from "./emailProposals";
import correspondentsRouter from "./correspondents";
import notesRouter from "./notes";
import tasksRouter from "./tasks";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(regionsRouter);
router.use(schoolsRouter);
router.use(lookupsRouter);
router.use(entitiesRouter);
router.use(fiscalYearEntityGoalsRouter);
router.use(householdsRouter);
router.use(paymentIntermediariesRouter);
router.use(fundersRouter);
router.use(organizationsRouter);
router.use(peopleRouter);
router.use(peopleEntityRolesRouter);
router.use(emailsRouter);
router.use(phoneNumbersRouter);
router.use(addressesRouter);
router.use(opportunitiesRouter);
router.use(pledgeAllocationsRouter);
router.use(giftsRouter);
router.use(giftAllocationsRouter);
router.use(analyticsRouter);
router.use(interactionsRouter);
router.use(googleOauthRouter);
router.use(googleSyncRouter);
router.use(emailMessagesRouter);
router.use(emailAttachmentsRouter);
router.use(calendarEventsRouter);
router.use(adminSyncRouter);
router.use(emailProposalsRouter);
router.use(correspondentsRouter);
router.use(notesRouter);
router.use(tasksRouter);
router.use(storageRouter);

export default router;
