import { defineConfig, InputTransformerFn } from "orval";
import path from "path";

const repoRoot = path.resolve(__dirname, "..", "..");
// CODEGEN_OUT_ROOT lets codegen-check.sh generate into a temp mirror of the
// repo layout (same relative paths, so generated imports are byte-identical)
// and diff against the committed output without ever mutating shared source
// while other checks run. Default (unset) writes into the real workspace.
const outRoot = process.env.CODEGEN_OUT_ROOT
  ? path.resolve(process.env.CODEGEN_OUT_ROOT)
  : repoRoot;
const apiClientReactSrc = path.resolve(outRoot, "lib", "api-client-react", "src");
const apiZodSrc = path.resolve(outRoot, "lib", "api-zod", "src");

// Our exports make assumptions about the title of the API being "Api" (i.e. generated output is `api.ts`).
const titleTransformer: InputTransformerFn = (config) => {
  config.info ??= {};
  config.info.title = "Api";

  return config;
};

export default defineConfig({
  "api-client-react": {
    input: {
      target: "./openapi.yaml",
      override: {
        transformer: titleTransformer,
      },
    },
    output: {
      workspace: apiClientReactSrc,
      target: "generated",
      client: "react-query",
      // Per-tag split: one small file per tag (plus a generated barrel)
      // instead of a single ~26k-line `api.ts`. Lets tsc skip unchanged tags
      // on incremental builds and keeps each regenerated file small.
      mode: "tags-split",
      baseUrl: "/api",
      clean: true,
      // Generated code does not need formatting; skipping prettier over ~47k
      // generated lines is the single biggest codegen speedup.
      prettier: false,
      // NB: leave indexFiles at its default (true) here. The react-query client
      // emits a single `api.schemas.ts`; with indexFiles:false orval rewrites the
      // tag files to import per-schema modules (`../api.schemas/<name>`) that are
      // never emitted, breaking the build. The root barrel is still produced by
      // gen-index.mjs (orval does not emit one for tags-split hooks).
      override: {
        fetch: {
          includeHttpResponseReturnType: false,
        },
        mutator: {
          path: path.resolve(apiClientReactSrc, "custom-fetch.ts"),
          name: "customFetch",
        },
      },
    },
  },
  zod: {
    input: {
      target: "./openapi.yaml",
      override: {
        transformer: titleTransformer,
      },
    },
    output: {
      workspace: apiZodSrc,
      client: "zod",
      target: "generated",
      mode: "tags-split",
      clean: true,
      prettier: false,
      // Barrel is generated by gen-index.mjs; keep orval from touching the
      // hand-authored src/index.ts (its invariant validators live there).
      indexFiles: false,
      override: {
        zod: {
          coerce: {
            query: ['boolean', 'number', 'string'],
            param: ['boolean', 'number', 'string'],
            body: ['bigint'],
            response: ['bigint'],
          },
        },
        useBigInt: true,
      },
    },
  },
});
