// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/detail-page-redesign/ActionRail.tsx": () => import("../components/mockups/detail-page-redesign/ActionRail.tsx"),
  "./components/mockups/detail-page-redesign/DossierZones.tsx": () => import("../components/mockups/detail-page-redesign/DossierZones.tsx"),
  "./components/mockups/detail-page-redesign/TabbedWorkspace.tsx": () => import("../components/mockups/detail-page-redesign/TabbedWorkspace.tsx"),
  "./components/mockups/reconciliation-cards/Pipeline.tsx": () => import("../components/mockups/reconciliation-cards/Pipeline.tsx"),
  "./components/mockups/reconciliation-cards/StatusRows.tsx": () => import("../components/mockups/reconciliation-cards/StatusRows.tsx"),
  "./components/mockups/reconciliation-cards/TwoLanes.tsx": () => import("../components/mockups/reconciliation-cards/TwoLanes.tsx"),
  "./components/mockups/record-redesign/FunderRecord.tsx": () => import("../components/mockups/record-redesign/FunderRecord.tsx"),
  "./components/mockups/record-redesign/IndividualRecord.tsx": () => import("../components/mockups/record-redesign/IndividualRecord.tsx"),
  "./components/mockups/workbench-redesign/GuidedTriage.tsx": () => import("../components/mockups/workbench-redesign/GuidedTriage.tsx"),
  "./components/mockups/workbench-redesign/LedgerInspector.tsx": () => import("../components/mockups/workbench-redesign/LedgerInspector.tsx"),
  "./components/mockups/workbench-redesign/StateBoard.tsx": () => import("../components/mockups/workbench-redesign/StateBoard.tsx")
};
