// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/record-redesign/FunderRecord.tsx": () => import("../components/mockups/record-redesign/FunderRecord.tsx"),
  "./components/mockups/record-redesign/IndividualRecord.tsx": () => import("../components/mockups/record-redesign/IndividualRecord.tsx")
};
