import { pgTable, text, timestamp, boolean, integer, date } from "drizzle-orm/pg-core";

export const people = pgTable("people", {
  id: text("id").primaryKey(),
  airtableId: text("airtable_id").unique(),
  prefix: text("prefix"),
  firstName: text("first_name"),
  nickname: text("nickname"),
  middleName: text("middle_name"),
  lastName: text("last_name"),
  suffix: text("suffix"),
  fullName: text("full_name"),
  pronouns: text("pronouns"),
  deceased: boolean("deceased").default(false).notNull(),
  householdName: text("household_name"),
  currentHomeRegionId: text("current_home_region_id"),
  details: text("details"),
  owner: text("owner"),
  tags: text("tags"),
  lastContacted: date("last_contacted"),
  interactionCount: integer("interaction_count"),
  createdFromCopper: date("created_from_copper"),
  updatedFromCopper: date("updated_from_copper"),
  linkedin: text("linkedin"),
  x: text("x"),
  facebook: text("facebook"),
  instagram: text("instagram"),
  aboutMe: text("about_me"),
  youtube: text("youtube"),
  website: text("website"),
  interestsThematic: text("interests_thematic").array(),
  interestsAges: text("interests_ages").array(),
  interestsGovModels: text("interests_gov_models").array(),
  newsletter: boolean("newsletter").default(false).notNull(),
  unsubscribedToNewsletter: boolean("unsubscribed_to_newsletter").default(false).notNull(),
  childrenAtWf: text("children_at_wf"),
  meetingLink: text("meeting_link"),
  assistantPersonId: text("assistant_person_id"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export type Person = typeof people.$inferSelect;
export type NewPerson = typeof people.$inferInsert;
